apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: registration
spec:
  hosts:
  - "*"
  http:
  - match:
    - uri:
        match: "/"
    rewrite:
      uri: "/mcasperson/NodejsProxy/master/externalservice1.txt"
      authority: raw.githubusercontent.com
    route:
    - destination:
        host: raw.githubusercontent.com
        port:
          number: 443
